name: Sync Bitbucket
on:
  push:
    branches:
      - "*"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: install rsync
        run: sudo apt-get install -y rsync
      - uses: actions/checkout@v3
        with:
          path: 'github'
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.BITBUCKET_URL }}
          path: 'bitbucket'
      - name: Copy files
        run: rsync -auvh github/ bitbucket/
      - name: commit
        run: |
          cd bitbucket/
          git fetch
          git pull
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -am "Github sync"
          git push
