name: Sync Bitbucket
on:
  push:
    branches:
      - "master"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: install rsync
        run: sudo apt-get install -y rsync
      - uses: actions/checkout@v3
        with:
          path: 'github'
      - name: Checkout from Bitpucket
        run: |
          mkdir bitbucket
          cd bitbucket
          git init
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote add origin ${{ secrets.BITBUCKET_URL }}
          git checkout origin/master
          cd ..
      - name: Copy files
        run: rsync -auvh --exclude '.git' github/ bitbucket/
      - name: commit
        run: |
          cd bitbucket/
         
          git add --all
          git commit -m "Update from GitHub"
          git push -u origin HEAD:master
