name: Sync Bitbucket
on:
  push:
    branches:
      - "*"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: install rsync
        run: sudo apt-get install -y rsync
      - uses: actions/checkout@v3
        with:
          path: 'github'
      - name: Checkout from Bitpucket
        run: |
          mkdir bitbucket
          cd bitbucket
          git clone ${{ secrets.BITBUCKET_URL }}
          cd ..
      - name: Copy files
        run: rsync -auvh --exclude '.git' github/ bitbucket/
      - name: commit
        run: |
          cd bitbucket/
          git init
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add --all
          git commit -m "Update from GitHub"
          git remote add origin https://andreas.scherer%40umb.ch:OTU5MTQ3MDU0NTU1OmFWzE8yAF6cuOByVSHgvbQn60AN@git.umb.cloud/scm/tne/fortiapi-snippets.git
          git pull
          git push -u origin HEAD:master
